### ISSUE TITLE
Advice explorer does not reproduce the graphs of Standard Graphs 

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/online-advice#266]
I picked a random stock and noticed discrepancies between the graphs in SAG and Advice Explorer. For instance, Advice required that SAG not display years without data to avoid misleading users. Could this feature also be implemented in Advice Explorer?

An examples is: https://standardgraphs.ices.dk/ViewCharts.aspx?key=18808 

![image](https://github.com/ices-tools-dev/adviceXplorer/assets/8705477/6ac5baf3-ec8e-4f96-b273-6ab5982adb70)

Note: It's also missing one of the reference points, this can be read in the web services of SAG.

**Comment by cmspinto** [comment]
Units need also to be checked, here is an example that can be used:
![image](https://github.com/ices-tools-dev/adviceXplorer/assets/8705477/cdb119b8-8934-4bc4-97a4-892da52b85c2)

**Comment by cmspinto** [comment]
The Advice explorer is not picking the name of the series. if you look at the series names that the stock coordinator put, it's not being followed by advice explorer.

https://[standardgraphs.ices.dk/ViewCharts.aspx?key=18958](https://standardgraphs.ices.dk/ViewCharts.aspx?key=18958)

In SAG the series is called FMSYproxy
![image](https://github.com/user-attachments/assets/9a3ddf95-0978-4029-ae4b-5ea3f9126819)

in AdviceExplorer it's just called F:

![image](https://github.com/user-attachments/assets/b90f5f9e-f8ec-41a7-b9d8-7bcafde93382)

Could this be fixed?

**Comment by lucalamoni** [comment]
Hi Carlos,
as I mentioned to you in person, the gaps in data (like in the red line) and the custom reference points (like FMSYproxy in blue) are fixed (but the fix is not deployed yet). Colin and I need to review the changes and then I'll deploy the updated app ASAP.
Thank you for spotting this inconsistency.
Cheers
Luca

**Comment by cmspinto** [comment]
Hi Luca, 
Sorry, this looked to me like a new bug. 
I would like to call to your attention, that this is not a reference point, it's the name of the series!
Do you think this will be fixed with the next deployment? Can you test this?

**Comment by cmspinto** [comment]
Have noticed there’s a new version of the Advice Explorer, great to see that some of the bugs have been fixed!

Just a quick heads-up: it seems that the units are still incorrect in some areas. For example, in the case of [bli.27.5a14]( https://standardgraphs.ices.dk/ViewCharts.aspx?key=18958), the displayed value is 2500, but in the database, it’s actually 2.5.

Here’s a visual to clarify:

![image](https://github.com/user-attachments/assets/25da82b7-a02d-4871-811f-8b99332c5576)


![image](https://github.com/user-attachments/assets/73a4819c-962f-4c08-b28b-c549f7af0d0c)

Could someone take a look at this when you get a chance?

**Comment by lucalamoni** [comment]
Hi @cmspinto, yes I fixed some of the issues mentioned above. As you noticed, I still need to fix the units for some stocks (that's why I haven't closed this ticket yet). I already agreed with Laura to meet so that she can explain to me how the units in the graphs are managed in SAG, that way I can adapt a similar method in adviceXplorer.

**Comment by lucalamoni** [comment]
@cmspinto In the examples above, the Y-axis units for the SSB plot have been fixed. However, this solution does not work for absolutely all stocks. After the holidays, I still plan to meet with Laura to find a more encompassing solution.

**Comment by cmspinto** [comment]
Thanks, @lucalamoni If you and Laura need any help, I’m happy to assist. This one is crucial.

**Comment by lucalamoni** [comment]
Hi @cmspinto, I corrected the Y-axis units issue listed above. Now the Y-units of the plots in adviceXplorer mirror the ones in SAG (thank you @LApetre for your help with this).
I could find 5 stocks that are still showing some inconsistencies and I have listed them here #288 . In case you find more you are welcome to add to that list. Thank you again for reporting this issue.
